PORT=$(expr $RANDOM + 1000)
GPUS=1
CUDA_VISIBLE_DEVICES=1	python train_kfold_with_xgboost.py \
		--model=RNN \
		--fp16=True \
		--desc_backbone="./pretrain/roberta_base" \
		--diff_backbone="./pretrain/microsoft_codebert-base"\
		--batch_size_per_gpu=100 \
		--learning_rate=2e-5 \
		--epochs=3 \
		--max_length=128 \
		--dataset_mode=word \
		--hide=False\
		--hide_dim=4\
		--nominize=True\
		--test=True \
		--train_dir=./inputs/train.csv \
		--val_dir=./inputs/val.csv \
        --test_dir=./inputs/test.csv \
		--save_model=True \
		--save_dir=./checkpoints/checkpoints-rnn-xgboost-10 \
		--log_name=logs.txt