sqlite3:
  path: "/data1/kexingchen/ePR.db"
  patch_path: "/data1/kexingchen/ePR_patch.db"

mongodb:
  host: "127.0.0.1"
  port: 27017
  db: "ePR"


raw_data: "/data1/kexingchen/star_50"

repo_dir: "/data1/kexingchen/star_50/clone_star_50_projects"

repo_list_file: "./project_list.json"
